In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import datetime
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv('2012-2013_cleaned.csv', index_col=0)

In [3]:
y=df['loan_status']

In [4]:
df.drop(columns=['emp_title','issue_d','zip_code','loan_status'], inplace=True)

In [5]:
real_part=df.iloc[:,:19]

In [6]:
dummy_part=df.iloc[:,19:]

In [7]:
scaler=StandardScaler()

In [8]:
scaler.fit(real_part)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
scaled=scaler.transform(real_part)

In [10]:
df1=pd.DataFrame(scaled, columns=real_part.columns)

In [11]:
df=pd.concat([df1,dummy_part], axis=1)

In [22]:
pca = PCA(n_components=20)

In [23]:
pca.fit(df)

PCA(copy=True, iterated_power='auto', n_components=20, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [24]:
x_pca = pca.transform(df)

In [25]:
df.shape

(176414, 91)

In [26]:
x_pca.shape

(176414, 20)

In [27]:
pca.explained_variance_ratio_

array([0.17742039, 0.15404269, 0.08998483, 0.07126932, 0.060466  ,
       0.0496795 , 0.0459755 , 0.03928151, 0.0353051 , 0.03203133,
       0.03003427, 0.02695624, 0.02250654, 0.02068537, 0.01558381,
       0.01470769, 0.01326762, 0.01291491, 0.01149148, 0.01067236])

In [33]:
df_real=df.iloc[:,:19]

In [36]:
pca = PCA(n_components=10)

In [37]:
pca.fit(df_real)

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [38]:
x_pca_real = pca.transform(df_real)

In [40]:
df_real.shape

(176414, 19)

In [41]:
x_pca_real.shape

(176414, 10)

In [42]:
pca.explained_variance_

array([3.87427915, 3.23690847, 1.98059281, 1.52001313, 1.30984316,
       1.05026314, 0.99751425, 0.86342739, 0.74808914, 0.68742189])

In [44]:
from sklearn.decomposition import TruncatedSVD

In [50]:
svd=TruncatedSVD(n_components=20)

In [51]:
svd.fit(df)

TruncatedSVD(algorithm='randomized', n_components=20, n_iter=5,
       random_state=None, tol=0.0)

In [52]:
x_svd=svd.transform(df)

In [53]:
svd.explained_variance_

array([3.91941249, 3.40337158, 1.22368102, 0.92104617, 1.50095223,
       1.3336899 , 1.09092213, 1.01573337, 0.86587812, 0.77953528,
       0.70235236, 0.65445802, 0.59556879, 0.49568466, 0.45696788,
       0.32645667, 0.32204164, 0.29312863, 0.2849186 , 0.24516707])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.30, random_state=101)

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(logmodel.score(X_test, y_test))

             precision    recall  f1-score   support

        0.0       0.85      1.00      0.92     44742
        1.0       0.46      0.01      0.02      8183

avg / total       0.79      0.85      0.78     52925

[[44639   103]
 [ 8095    88]]
0.8451015588096363


In [21]:
logmodel = LogisticRegression(class_weight='balanced')
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(logmodel.score(X_test, y_test))

             precision    recall  f1-score   support

        0.0       0.90      0.64      0.75     44742
        1.0       0.24      0.63      0.35      8183

avg / total       0.80      0.64      0.69     52925

[[28662 16080]
 [ 3031  5152]]
0.6389041095890411
