In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
df=pd.read_csv('2012-2013_cleaned.csv', index_col=0)
y=df['loan_status']
df.drop(columns=['emp_title','issue_d','zip_code','loan_status'], inplace=True)
real_part=df.iloc[:,:19]
dummy_part=df.iloc[:,19:]
scaler=StandardScaler()
scaler.fit(real_part)
scaled=scaler.transform(real_part)
df1=pd.DataFrame(scaled, columns=real_part.columns)
df=pd.concat([df1,dummy_part], axis=1)
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.30, random_state=101)

In [3]:
rfc = RandomForestClassifier(n_estimators=100, verbose=5)


In [4]:
rfc.fit(X_train, y_train)

building tree 1 of 100


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s


building tree 2 of 100


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s


building tree 3 of 100


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.8s remaining:    0.0s


building tree 4 of 100


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    1.0s remaining:    0.0s


building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 1

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   24.4s finished


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=5,
            warm_start=False)

In [5]:
rfc_pred = rfc.predict(X_test)

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    1.5s finished


In [6]:
print(confusion_matrix(y_test,rfc_pred))

[[44694    48]
 [ 8121    62]]


In [8]:
print(classification_report(y_test,rfc_pred))

             precision    recall  f1-score   support

        0.0       0.85      1.00      0.92     44742
        1.0       0.56      0.01      0.01      8183

avg / total       0.80      0.85      0.78     52925



In [8]:
rfc.feature_importances_

array([4.76704016e-02, 5.35755777e-02, 5.58348605e-02, 4.20819542e-02,
       3.20861874e-02, 5.76246691e-02, 6.14943284e-02, 1.07351701e-02,
       5.82629009e-02, 3.25435465e-02, 3.16394334e-02, 2.03292730e-02,
       4.09722214e-02, 6.00200522e-02, 5.81713639e-02, 4.81129487e-02,
       3.68075984e-02, 2.42421221e-02, 3.47553236e-02, 7.77310983e-03,
       7.55881089e-03, 6.53157065e-03, 6.00558947e-05, 1.43951393e-04,
       4.37416837e-03, 6.74458403e-03, 5.45209156e-03, 7.10050848e-03,
       7.66747641e-03, 1.11280914e-03, 6.48382133e-03, 8.11120639e-03,
       3.43600915e-03, 1.16215713e-03, 1.88028896e-03, 1.19274331e-03,
       9.30214644e-04, 3.47206955e-03, 2.37391695e-04, 2.60691088e-03,
       7.72159241e-04, 9.02894888e-04, 6.40322426e-04, 2.16315232e-03,
       1.61862154e-03, 3.03092626e-03, 7.79414709e-03, 2.26108491e-03,
       2.34106912e-03, 4.20261271e-04, 6.43145909e-04, 5.71174747e-03,
       3.20652976e-03, 1.23601506e-03, 2.33498733e-05, 0.00000000e+00,
      

In [10]:
from sklearn.model_selection import GridSearchCV

In [11]:
param_grid={'criterion':['gini','entropy'],'max_features':['sqrt','log2',None],
           'class_weight':['balanced','balanced_subsample',None]}


In [12]:
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit=True, error_score=0, verbose=5)

In [13]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
[CV] class_weight=balanced, criterion=gini, max_features=sqrt ........
[CV]  class_weight=balanced, criterion=gini, max_features=sqrt, score=0.8409289670585949, total=   1.7s
[CV] class_weight=balanced, criterion=gini, max_features=sqrt ........


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.0s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=sqrt, score=0.8402934674343464, total=   1.7s
[CV] class_weight=balanced, criterion=gini, max_features=sqrt ........


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.9s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=sqrt, score=0.8392692289004422, total=   1.7s
[CV] class_weight=balanced, criterion=gini, max_features=log2 ........


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    5.9s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=log2, score=0.8403459333398114, total=   1.4s
[CV] class_weight=balanced, criterion=gini, max_features=log2 ........


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    7.5s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=log2, score=0.8396861258897553, total=   1.4s
[CV] class_weight=balanced, criterion=gini, max_features=log2 ........
[CV]  class_weight=balanced, criterion=gini, max_features=log2, score=0.8407025897672611, total=   1.4s
[CV] class_weight=balanced, criterion=gini, max_features=None ........
[CV]  class_weight=balanced, criterion=gini, max_features=None, score=0.8370906617432708, total=  13.5s
[CV] class_weight=balanced, criterion=gini, max_features=None ........
[CV]  class_weight=balanced, criterion=gini, max_features=None, score=0.8374996963292277, total=  12.6s
[CV] class_weight=balanced, criterion=gini, max_features=None ........
[CV]  class_weight=balanced, criterion=gini, max_features=None, score=0.8361109761430445, total=  10.2s
[CV] class_weight=balanced, criterion=entropy, max_features=sqrt .....
[CV]  class_weight=balanced, criterion=entropy, max_features=sqrt, score=0.839835778835876, total=   1.8s
[CV] class_weight=b

[CV]  class_weight=None, criterion=entropy, max_features=log2, score=0.8398037024440017, total=   1.6s
[CV] class_weight=None, criterion=entropy, max_features=None .........
[CV]  class_weight=None, criterion=entropy, max_features=None, score=0.8391798659022447, total=  11.8s
[CV] class_weight=None, criterion=entropy, max_features=None .........
[CV]  class_weight=None, criterion=entropy, max_features=None, score=0.8377426329470641, total=  11.9s
[CV] class_weight=None, criterion=entropy, max_features=None .........
[CV]  class_weight=None, criterion=entropy, max_features=None, score=0.8372042174821437, total=  11.4s


[Parallel(n_jobs=1)]: Done  54 out of  54 | elapsed:  4.9min finished


GridSearchCV(cv=None, error_score=0,
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_features': ['sqrt', 'log2', None], 'class_weight': ['balanced', 'balanced_subsample', None]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=5)

In [14]:
grid.best_params_

{'class_weight': 'balanced_subsample',
 'criterion': 'gini',
 'max_features': 'log2'}

In [15]:
grid_predictions = grid.predict(X_test)
print(classification_report(y_test,grid_predictions))
print(confusion_matrix(y_test,grid_predictions))
print(grid.score(X_test, y_test))

             precision    recall  f1-score   support

        0.0       0.85      0.99      0.91     44742
        1.0       0.34      0.03      0.05      8183

avg / total       0.77      0.84      0.78     52925

[[44317   425]
 [ 7960   223]]
0.8415682569674067


In [17]:
grid2 = GridSearchCV(RandomForestClassifier(), param_grid, scoring='roc_auc', refit=True, error_score=0, verbose=5)

In [18]:
grid2.fit(X_train,y_train)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
[CV] class_weight=balanced, criterion=gini, max_features=sqrt ........
[CV]  class_weight=balanced, criterion=gini, max_features=sqrt, score=0.615897392095621, total=   1.8s
[CV] class_weight=balanced, criterion=gini, max_features=sqrt ........


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=sqrt, score=0.615052610611563, total=   1.8s
[CV] class_weight=balanced, criterion=gini, max_features=sqrt ........


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    4.2s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=sqrt, score=0.615865582029007, total=   1.9s
[CV] class_weight=balanced, criterion=gini, max_features=log2 ........


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    6.3s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=log2, score=0.6073371576938942, total=   1.5s
[CV] class_weight=balanced, criterion=gini, max_features=log2 ........


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    8.1s remaining:    0.0s


[CV]  class_weight=balanced, criterion=gini, max_features=log2, score=0.6189670725153283, total=   1.6s
[CV] class_weight=balanced, criterion=gini, max_features=log2 ........
[CV]  class_weight=balanced, criterion=gini, max_features=log2, score=0.6184103009007038, total=   1.6s
[CV] class_weight=balanced, criterion=gini, max_features=None ........
[CV]  class_weight=balanced, criterion=gini, max_features=None, score=0.6151447467409322, total=  11.2s
[CV] class_weight=balanced, criterion=gini, max_features=None ........
[CV]  class_weight=balanced, criterion=gini, max_features=None, score=0.6176797596813661, total=  10.6s
[CV] class_weight=balanced, criterion=gini, max_features=None ........
[CV]  class_weight=balanced, criterion=gini, max_features=None, score=0.610284619148461, total=  10.6s
[CV] class_weight=balanced, criterion=entropy, max_features=sqrt .....
[CV]  class_weight=balanced, criterion=entropy, max_features=sqrt, score=0.6239017560122009, total=   2.2s
[CV] class_weight=b

[CV]  class_weight=None, criterion=entropy, max_features=log2, score=0.6153101836155728, total=   1.6s
[CV] class_weight=None, criterion=entropy, max_features=None .........
[CV]  class_weight=None, criterion=entropy, max_features=None, score=0.6203288093028495, total=  12.6s
[CV] class_weight=None, criterion=entropy, max_features=None .........
[CV]  class_weight=None, criterion=entropy, max_features=None, score=0.6227863559614053, total=  13.0s
[CV] class_weight=None, criterion=entropy, max_features=None .........
[CV]  class_weight=None, criterion=entropy, max_features=None, score=0.6179089295877627, total=  12.3s


[Parallel(n_jobs=1)]: Done  54 out of  54 | elapsed:  5.1min finished


GridSearchCV(cv=None, error_score=0,
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_features': ['sqrt', 'log2', None], 'class_weight': ['balanced', 'balanced_subsample', None]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=5)

In [19]:
grid2.best_params_

{'class_weight': None, 'criterion': 'entropy', 'max_features': 'sqrt'}

In [20]:
grid2_predictions = grid2.predict(X_test)
print(classification_report(y_test,grid2_predictions))
print(confusion_matrix(y_test,grid2_predictions))
print(grid2.score(X_test, y_test))

             precision    recall  f1-score   support

        0.0       0.85      0.99      0.91     44742
        1.0       0.33      0.03      0.06      8183

avg / total       0.77      0.84      0.78     52925

[[44201   541]
 [ 7918   265]]
0.61835481511163
